[project]
name = "ws-django-suit"
version = "1.0.1"
description = "Modern theme for Django admin interface."
authors = [
    { name = "Kaspars Sprogis", email = "info@djangosuit.com" }
]
maintainers = [
    { name = "Evgeniy Medvedev", email = "yevgeniy.medvedev@gmail.com" },
]
requires-python = ">=3.12,<3.14"

[tool.poetry]
package-mode = true
packages = [
    { include = "suit" },
]

[[tool.poetry.source]]
name = "ws"
url = "https://pypi.wheel-size.com/simple/"

[tool.poetry.dependencies]
django = ">=4.2,<5.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
